### ISSUE TITLE
Program exit when I use 'Scan For Games'

### ISSUE THREAD

**Issue by zouyonghao** [JupiterJesus/SwitchManager#1]
Program exit when I use 'Scan For Games'

Is this a function for scaning a directory where .nsp files are?

**Comment by JupiterJesus** [comment]
It is. I don't give tech support, but try release 1.2.1. If it still crashes, paste the contents of default.log. I use the app every day and it works fine, but I haven't done a full library scan in a while.

Release 1.2 does a lot to handle and hide errors and makes the app more stable and useful since cdn access was terminated.

**Comment by zouyonghao** [comment]
Thanks, I'll try 1.2 later.

**Comment by IceMarker** [comment]
Is this program still working?
I tried to compile and run, no error, but no data
